version: '3'

services:
  rest-messages:
    container_name: rest-messages
    build: .
    environment:
      - DB_HOST = mysql
      - DB_USER = root
      - DB_PASSWORD = password
    ports:
      - "8083:8080"
    network_mode: bridge